#!/bin/bash
read  -e -p "输入安装路径" LuJing
read  -e -p "输入证书天数" TianShu
openssl genpkey -algorithm RSA -out $LuJing/server.key

openssl req -new -key $LuJing/server.key -out $LuJing/server.csr

openssl x509 -req -days $TianShu -in $LuJing/server.csr -signkey $LuJing/server.key -out $LuJing/server.crt

